
# environment settings

nw_size: 7 # [7, 12, 17, 22]
mu: 0.8
beta: 0.0    # [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
init_txr: 0
source_init_txr: 2

utility_coeff: 1.0 # [1.0, 3.0, 5.0, 7.0]
utility_pos_coeff: 5


??action_space


# learning settings
lr: 0.01
num_ep: 30
ep_length: 150
gamma: 0.7 # discount factor